### PR TITLE
Update run-analyzer-macos-linux.md

### PR DESCRIPTION
**Pull request by EdgarPMIA**
Adding a note to clarify that the report.html file is generated only when using the Python-based version of the client analyzer. I looked for the file but couldn't find. When I used the Python-based version of the client analyzer, I confirmed the file was generated.

### CODE REVIEW

**Comment by EdgarPMIA** [comment]
Anything additional I need to do to finish the update on this article? thanks!

**Comment by siosulli** [comment]
> Anything additional I need to do to finish the update on this article? thanks!

Thanks @EdgarPMIA! What you added looks great. I actually find the original sentence a bit confusing :).

"The main HTML output file that contains the findings and guidance that the analyzer script run on the machine can produce"

If we updated it to this - does this make sense:

"The main HTML output file that contains the findings and guidance from running the client analyzer tool on the device. This file is only generated when running the Python-based version of the client analyzer tool. "

**Comment by EdgarPMIA** [comment]
@siosulli Hi, yes, I think is perfect 👌

**Comment by siosulli** [comment]
Great! I will make the update and go ahead merge. Thank you!

**Pull request merged**
